### ISSUE TITLE
Access to trained models

### ISSUE THREAD

**Issue by reubano** [owkin/DSB2017#1]
Hi. Would you be able to provide access to your trained models? Thanks!

**Comment by SimJeg** [comment]
Hi Reubano, 

You can find the trained neural networks for nodule segmentation in the different folders : 
Pierre's model : model64x64x64_v5_rotate_v2.h5
Simon's model : Unet_{X,Y,Z}.h5

We didn't store the xgboost trees so you need to generate the features (can be hours) and then train xgboost (very fast).

Simon

**Comment by guyucowboy** [comment]
Hi, Simon. 
It is a great work!
How can I see the model  architecture in detail from hdf5 files ? 
I really want to learn it.
Thanks.
Gu Yu
